name: CI

on:
  push:
    branches: [releases/**, main]
    tags:
      - '*'
    paths:
      - '.github/workflows/**'
      - 'amplify/backend/**'
      - 'src/**'
      - 'package.json'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/**'
      - 'amplify/backend/**'
      - 'src/**'
      - 'package.json'

env:
  NODE_VERSION: 18.x

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: CI
        uses: actions/checkout@v3
      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/cache@v3
        with:
          path: '**/amplify/backend/function/bpr2lambda1/src/node_modules'
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies for frontend
        run: yarn install
        env:
          CI: true
      - name: Install dependencies for backend
        run: cd amplify/backend/function/bpr2lambda1/src && yarn install
        env:
          CI: true

  lint:
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - name: Running lint
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Lint
        run: yarn lint
        env:
          CI: true

  test:
    runs-on: ubuntu-latest
    needs: [install, lint]

    steps:
      - name: Running tests
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/cache@v3
        with:
          path: '**/amplify/backend/function/bpr2lambda1/src/node_modules'
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies for backend
        run: cd amplify/backend/function/bpr2lambda1/src && yarn install && cd -
        env:
          CI: true
      - name: Test
        run: yarn test
        env:
          CI: true

  build:
    runs-on: ubuntu-latest
    needs: [install, lint, test]

    steps:
      - name: Build
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Configure Amplify
        uses: ambientlight/amplify-cli-action@0.3.0
        with:
          amplify_command: configure
          amplify_env: dev
          amplify_cli_version: 12.5.1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1 
      - name: Build
        run: yarn build
      - name: Release
        uses: cycjimmy/semantic-release-action@v2.7.0
        id: semantic
        with:
          branch: main
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
